export * as londonSchoolOfEconomics from './london-school-of-economics'
export * as schoolOfAdvancedStudy from './school-of-advanced-study'
export * as francisCrickInstitute from './francis-crick-institute'
// export * as alanTuringInstitute from './alan-turing-institute'
export * as welcomeCollection from './welcome-collection'
export * as guildhallLibrary from './guildhall-library'
export * as thebritishacademy from './british-academy'
export * as royalsociety from './royal-society'
export * as goldsmiths from './goldsmiths'
export * as birckbeck from './birckbeck'
export * as cambridge from './cambridge'
export * as kingston from './kingston'
export * as aaschool from './aaschool'
export * as imperial from './imperial'
export * as gresham from './gresham'
export * as kings from './kings'
export * as oxford from './oxford'
export * as soas from './soas'
export * as rsa from './rsa'
export * as ucl from './ucl'
// export * as ra from './ra'
// export * as va from './va'
