name: Preview

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm run build:ts

      - name: Install dependancies
        run: pnpm install

      - name: Scrape lectures
        run: pnpm run collect

      - name: Get ref uri
        id: get-ref-uri
        run: echo ref_name=$(echo "refs/pull/1/merge" | tr / -) >> $GITHUB_OUTPUT

      - name: Build client
        run: pnpm run build:client
        env:
          SITE_URL: https://${{ env.BRANCH_NAME }}--${{ secrets.NETLIFY_SITE_NAME }}.netlify.app

      - name: Deploy to netlify
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          build_directory: '@client/build/client'
          functions_directory: '@client/build/functions'
          install_command: 'echo Skipping installing the dependencies'
          build_command: 'echo Skipping building the web files'
          deploy_alias: ${{ env.BRANCH_NAME }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: 'Actions preview ${{ env.BRANCH_NAME }}'

      - name: Status check
        uses: Sibz/github-status-action@v1.1.1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Netlify preview
          state: success
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: https://${{ env.BRANCH_NAME }}--${{ secrets.NETLIFY_SITE_NAME }}.netlify.app
